spring.application.name=pdv-galeteria
spring.datasource.url=jdbc:postgresql://localhost:5432/pdv_galeteria
spring.datasource.username=pdv_user
spring.datasource.password=GaletoPDV
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
